config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task

  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#delete', as: :delete_task

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update delete]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@tasks)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@tasks)
  end

  def delete
    @task.delete
    redirect_to tasks_path
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :checkbox_value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="mx-3">
  <%= form_with model: @task do |f| %>
    <div class="mb-3">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :details, class: 'form-label' %>
      <%= f.text_area :details, class: 'form-control' %>
   </div>
   <div class="field">
      <%= f.check_box :completed, class: 'form-control' %>
      <%= f.label :completed, class: 'form-label' %>
   </div>
   <div class="mb-3">
      <%= f.submit  class: 'btn btn-sm btn-primary' "edit" %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>

  <%= render 'form', task: @task %>
  <%= link_to 'back', tasks_path,  class: 'btn btn-sm btn-primary' %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<hr>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%# <%= check_box "task_completed_#{task.id}", '1', task.completed %> %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to 'edit', edit_task_path(task) %>
      <%= link_to 'delete', delete_task_path(task),
  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>

  <%= render 'form', task: @task %>
  <%= link_to 'Back to list', tasks_path %>
</div>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to 'Back to list', tasks_path %>